### ISSUE TITLE
develop - ECM wave not shown anymore when triggered

### ISSUE THREAD

**Issue by Bertram25** [stephenjsweeney/tbftss#10] opened 2016-02-15 13:08 UTC
The ECM shield circle isn't displayed anymore when pressing D, while the ECM progress bar is depleted.

**Comment by stephenjsweeney** [comment] 2016-02-16 09:36
Bug caused by some of the effects refactoring. Fixed in develop.

**Closed by stephenjsweeney** 2016-02-16 09:36 UTC
